/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface MgArrowIcon {
    }
    interface MgCourseLoader {
        "active": boolean;
        "course": {
    code: string;
    unit: string;
    completed: number;
    downloadable: boolean;
    downloaded: boolean;
  };
    }
    interface MgHome {
    }
    interface MgMinusIcon {
    }
    interface MgPlusIcon {
    }
    interface MgStudyCard {
        "courses": {
    code: string;
    unit: string;
    completed: number;
    downloadable: boolean;
    downloaded: boolean;
  }[];
        "endDate": string;
        "startDate": string;
        "week": string;
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLMgArrowIconElement extends Components.MgArrowIcon, HTMLStencilElement {
    }
    var HTMLMgArrowIconElement: {
        prototype: HTMLMgArrowIconElement;
        new (): HTMLMgArrowIconElement;
    };
    interface HTMLMgCourseLoaderElement extends Components.MgCourseLoader, HTMLStencilElement {
    }
    var HTMLMgCourseLoaderElement: {
        prototype: HTMLMgCourseLoaderElement;
        new (): HTMLMgCourseLoaderElement;
    };
    interface HTMLMgHomeElement extends Components.MgHome, HTMLStencilElement {
    }
    var HTMLMgHomeElement: {
        prototype: HTMLMgHomeElement;
        new (): HTMLMgHomeElement;
    };
    interface HTMLMgMinusIconElement extends Components.MgMinusIcon, HTMLStencilElement {
    }
    var HTMLMgMinusIconElement: {
        prototype: HTMLMgMinusIconElement;
        new (): HTMLMgMinusIconElement;
    };
    interface HTMLMgPlusIconElement extends Components.MgPlusIcon, HTMLStencilElement {
    }
    var HTMLMgPlusIconElement: {
        prototype: HTMLMgPlusIconElement;
        new (): HTMLMgPlusIconElement;
    };
    interface HTMLMgStudyCardElement extends Components.MgStudyCard, HTMLStencilElement {
    }
    var HTMLMgStudyCardElement: {
        prototype: HTMLMgStudyCardElement;
        new (): HTMLMgStudyCardElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "mg-arrow-icon": HTMLMgArrowIconElement;
        "mg-course-loader": HTMLMgCourseLoaderElement;
        "mg-home": HTMLMgHomeElement;
        "mg-minus-icon": HTMLMgMinusIconElement;
        "mg-plus-icon": HTMLMgPlusIconElement;
        "mg-study-card": HTMLMgStudyCardElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface MgArrowIcon {
    }
    interface MgCourseLoader {
        "active"?: boolean;
        "course"?: {
    code: string;
    unit: string;
    completed: number;
    downloadable: boolean;
    downloaded: boolean;
  };
    }
    interface MgHome {
    }
    interface MgMinusIcon {
    }
    interface MgPlusIcon {
    }
    interface MgStudyCard {
        "courses"?: {
    code: string;
    unit: string;
    completed: number;
    downloadable: boolean;
    downloaded: boolean;
  }[];
        "endDate"?: string;
        "startDate"?: string;
        "week"?: string;
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "mg-arrow-icon": MgArrowIcon;
        "mg-course-loader": MgCourseLoader;
        "mg-home": MgHome;
        "mg-minus-icon": MgMinusIcon;
        "mg-plus-icon": MgPlusIcon;
        "mg-study-card": MgStudyCard;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "mg-arrow-icon": LocalJSX.MgArrowIcon & JSXBase.HTMLAttributes<HTMLMgArrowIconElement>;
            "mg-course-loader": LocalJSX.MgCourseLoader & JSXBase.HTMLAttributes<HTMLMgCourseLoaderElement>;
            "mg-home": LocalJSX.MgHome & JSXBase.HTMLAttributes<HTMLMgHomeElement>;
            "mg-minus-icon": LocalJSX.MgMinusIcon & JSXBase.HTMLAttributes<HTMLMgMinusIconElement>;
            "mg-plus-icon": LocalJSX.MgPlusIcon & JSXBase.HTMLAttributes<HTMLMgPlusIconElement>;
            "mg-study-card": LocalJSX.MgStudyCard & JSXBase.HTMLAttributes<HTMLMgStudyCardElement>;
        }
    }
}
